favicon: null
name: The Jerseys - Colorado
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5
  brandStrength: 0.75
  rhythmicContrast: 0.5
  brandColors:
    - '#00020d'
    - '#1993fb'
    - '#ea364f'
    - '#dfe6df'
    - '#957775'
  lightness: 0.5
typography_spectrum: 0.49807
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.387218
analytics:
  twitter: null
  google: null
  facebook: null
