name: The Jerseys - Colorado
favicon: null
layout_spectrum: 0.9894
typography_spectrum: 0.49807
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00020d'
    - '#1993fb'
    - '#ea364f'
    - '#dfe6df'
    - '#957775'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
