name: The Jerseys - Colorado
favicon: null
layout_spectrum: 0.00484
typography_spectrum: 0.49807
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: The Jerseys Colorado
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77127740-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00020e'
    - '#1992fb'
    - '#a5111f'
    - '#735f4f'
    - '#f1ebed'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
