name: The Jerseys - Colorado
favicon: null
layout_spectrum: 0.76204
typography_spectrum: 0.49807
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00010d'
    - '#94959a'
    - '#09528b'
    - '#f23e57'
    - '#fcf0fa'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
